# Generated by Django 3.0 on 2019-12-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pySquashCode', models.CharField(blank=True, max_length=10, null=True)),
                ('pyName', models.CharField(max_length=100)),
                ('pyRank', models.IntegerField()),
                ('pyGradedFlag', models.NullBooleanField()),
                ('pyGrade', models.CharField(blank=True, max_length=10, null=True)),
                ('pyPoint', models.IntegerField(blank=True, null=True)),
                ('pyNote', models.CharField(blank=True, max_length=10000, null=True)),
                ('pyTimeMustGreater', models.TimeField(blank=True, null=True)),
                ('pyTimeMustLower', models.TimeField(blank=True, null=True)),
                ('pyPlayTwiceFlag', models.NullBooleanField()),
                ('pyMemberFlag', models.NullBooleanField()),
                ('pyStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Away', 'Away')], default='Active', max_length=10)),
                ('pyClass', models.CharField(choices=[('Juniors', 'Juniors'), ('Seniors', 'Seniors')], default='Juniors', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scClass', models.CharField(max_length=20)),
                ('scDate', models.DateField()),
                ('scTime', models.TimeField()),
                ('scTimeBreak', models.BooleanField(default=True)),
                ('scPlayer1Score', models.IntegerField(default=0)),
                ('scPlayer2Score', models.IntegerField(default=0)),
                ('scPlayer1Name', models.CharField(blank=True, max_length=100, null=True)),
                ('scPlayer1Rank', models.IntegerField(blank=True, null=True)),
                ('scPlayer2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('scPlayer2Rank', models.IntegerField(blank=True, null=True)),
                ('scDraft', models.BooleanField(default=True)),
                ('scPlayer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1_info', to='squash_draw.Player')),
                ('scPlayer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2_info', to='squash_draw.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhDate', models.DateField()),
                ('rhRank', models.IntegerField()),
                ('rhPlayerName', models.CharField(blank=True, max_length=100, null=True)),
                ('rhPlayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_info', to='squash_draw.Player')),
            ],
        ),
    ]
